# Generated by Django 3.2.9 on 2021-12-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Enter description of task', max_length=1000)),
                ('priority', models.IntegerField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
