# Generated by Django 3.2.9 on 2021-12-06 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainTodo', '0003_task_due_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
