# Generated by Django 3.2.9 on 2021-12-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainTodo', '0006_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
