# Generated by Django 3.2.9 on 2021-12-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainTodo', '0007_remove_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(help_text='Enter description of task', max_length=1000),
        ),
    ]
